language: cpp
matrix:
  include:

  # GCC Optimizations start
  - name: Ubuntu with gcc on amd64 and -O0
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_gcc_o0
      - CXXFLAGS="-O0"

  - name: Ubuntu with gcc on amd64 and -O1
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_gcc_o1
      - CXXFLAGS="-O1"

  - name: Ubuntu with gcc on amd64 and -O2
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_gcc_o2
      - CXXFLAGS="-O2"

  - name: Ubuntu with gcc on amd64 and -O3
    os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_gcc_o3
      - CXXFLAGS="-O3"
  # end GCC optimizations 

  # clang amd64 start
  - name: Ubuntu with clang on amd64 and -O0
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_clang_o0
      - CXXFLAGS="-O0"

  - name: Ubuntu with clang on amd64 and -O1
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_clang_o1
      - CXXFLAGS="-O1"

  - name: Ubuntu with clang on amd64 and -O2
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_clang_o2
      - CXXFLAGS="-O2"

  - name: Ubuntu with clang on amd64 and -O3
    os: linux
    dist: bionic
    compiler: clang
    arch: amd64
    env: 
      - TPCP_OPTIONS=amd64_linux_clang_o3
      - CXXFLAGS="-O3"
    # end clang

  # attempt a windows build
  # - name: Windows with gcc on amd64 and -O3
  #   os: windows
  #   arch: amd64
  #   env: 
  #     - TPCP_OPTIONS=amd64_Windows_gcc_o3
  #     - CXXFLAGS="-O3"
before_install:
- export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
- export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
- if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get update && sudo apt-get install
  -y texinfo; fi
script:
- mkdir -p build
- cd build
- ../configure
- make && make sqlite3.c
- cp sqlite3 sqlite3_${TPCP_OPTIONS}
branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"
deploy:
  provider: releases
  api_key:
    secure: S52UNs8KAcBroDHI5ctcDAhspsQ13UDeWOsPvrQM2xaUJe5TpfayxXmzywg6qB8fEjQ070mV1IS1RwsPxpqsjMG9ykMTbBrVeLAuqHvDxfV7sog5w6T2s39wiyMUzCyUfV/Y0CgygEQtVfWCesAvlYRsyAqpCtV36meXt8feMzURtXpmMrWemFuS332yDvQcQJ+eIxejsyNdabgeLzXE21RBnyP+mg9B01SEnTPyPRu9IV/x22y662rLXdPyFyAyQtMPyKGnW/ZMWbO8HURAkbLUOwoM07F+HaTWTGFQg3lyVbY9hgDD22bkWiyVW1CGqDyZpr8Ir1ASvFYFIA0RDNxWk3qa40YXoOyJ9KuDiJepE3i/6rbF0Xe8MV+6eJ1AMPL4uuDh7ueqEl3E/AJJYXx2AlKOcBhHy/zPIwW4KtE8D7j4PqSzZ9xy2/NcVRNoSaWeb4k8/c7Zdxss5eujNK7I7pmsfYvc+sV/l3Lnm5OEGXpRleIqx/o3xThqw204bpObtt9x2YmYM5caTI3lrC4eqiQrjbxi3G4RDbIp4M14Oe0FD2awmjqadgl4NtzhDRlZGySfi0eNYDDKM9BHBSFCHkTUiZKgJ5302Nzk2nokn/4DXDHISyNZiyJMijRYwE4mx/HauU+TAFkmdpeBjGkqS4ud380My5r7t0ezmAs=
  file_glob: true
  file: sqlite3*
  skip_cleanup: true
  on:
    repo: tpcp-project/sqlite
